Bugfix/missing deps
nmshd/cns-iql pull request #2
Opened 2023-07-12 07:00 UTC by slavistan

Includes github issue template, VSCode settings and a missing dev dependency. No version bump as packaged files are not affected.

2023-07-12 07:02 UTC, jkoenig134 commented on package.json
> +        "test": "npm run build && npx run lint && npx mocha ./dist/tests/**/*.test.js",
why do you run lint here?

2023-07-12 07:04 UTC, jkoenig134 commented
please add a license file including the MIT license

2023-07-12 07:06 UTC, jkoenig134 requested changes

2023-07-12 07:06 UTC, jkoenig134 commented on package.json
can you please run `npx sort-package-json`? That should make this more similar to our other package jsons

2023-07-12 07:06 UTC, jkoenig134 commented on package.json
> +        "test": "npm run build && npx run lint && npx mocha ./dist/tests/**/*.test.js",
typically we have the following scripts in addition:

```json
{
        "lint": "npm run lint:prettier && npm run lint:eslint && npm run lint:tsc",
        "lint:eslint": "eslint --ext .ts ./src ./test",
        "lint:prettier": "prettier --check .",
        "lint:tsc": "tsc --noEmit && tsc -p test/tsconfig.json --noEmit"
}
```

but you can also do the typechecking in another step

2023-07-12 07:07 UTC, jkoenig134 commented
please also add a test pipeline

2023-07-18 05:37 UTC, jkoenig134 commented on .prettierignore
> +/demo/_bundle.js
you should also ignore `dist` and `generated` here

2023-07-18 05:37 UTC, jkoenig134 commented on LICENSE
> +Copyright 2021 j&s-soft GmbH
2023

2023-07-18 05:38 UTC, jkoenig134 commented on README.md
the README is still not compliant to our readmes. Plase move this readme to README_dev.md and create a README.md that matches our other readmes.

2023-07-18 05:39 UTC, jkoenig134 commented on .github/workflows/publish-npmjs.yml
> -          npm ci && npm test
this should also be run in a dedicated test pipeline to make sure that we do not encounter any regression errors

2023-07-24 08:56 UTC, jkoenig134 requested changes

2023-07-24 08:56 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +name: Publish on npmjs.com
```suggestion
name: Publish
```

2023-07-24 08:56 UTC, jkoenig134 commented on .github/workflows/test.yml
> +    run-checks:
```suggestion
    test:
```

2023-07-24 12:39 UTC, jkoenig134 commented on .github/workflows/test.yml
> +            - run: ./.ci/runChecks.sh
see comment above. this should be an extra job

2023-07-24 12:40 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +            - run: npm publish --access public
you missed the part in the p json

2023-07-24 12:51 UTC, slavistan commented on .github/workflows/publish.yml
> +            - run: npm publish --access public
Does `enhanced-publish` accept the `--access public` flag? I'd rather not split up the options between the commandline *and* a configuration file.

2023-07-24 12:52 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +            - run: npm publish --access public
it does, but we split it in every project, so we will also split it here.

2023-07-24 12:54 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +        steps:
yaml is kind of                                spacy. Do you use the correct prettier config?

2023-07-24 12:54 UTC, jkoenig134 commented on package.json
> +    "dependencies": {},
empty deps object

2023-07-24 13:33 UTC, slavistan commented on .github/workflows/publish.yml
> +        steps:
I'm using this project's prettier config.

2023-07-24 13:39 UTC, jkoenig134 commented on .github/workflows/publish.yml
> +        steps:
I see, its wrong *this projects* prettier config is wrong :)

```json
{
    "endOfLine": "lf",
    "printWidth": 120,
    "tabWidth": 4,
    "trailingComma": "none",
    "semi": false,
    "arrowParens": "always",
    "overrides": [
        {
            "files": ["*.yaml", "*.yml"],
            "options": {
                "tabWidth": 2
            }
        }
    ]
}
```
should be the correct one

2023-07-24 14:11 UTC, jkoenig134 approved these changes

2023-07-24 16:50 UTC, merged